name: "❌ Report a Bug"
description: Create an issue if something does not work as expected.
labels: ["Priority/Normal", "Type/Bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: Description of the issue
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps you followed when you encountered the issue. If none, type N/A.
      placeholder: Steps to reproduce the behavior
    validations:
      required: true
  - type: dropdown
    id: affected
    attributes:
      label: Affected Component/Version
      multiple: true
      options:
        - APIM/2.6.0
        - APIM/3.0.0
        - APIM/3.1.0
        - APIM/3.2.0
        - APIM/4.0.0
        - APIM/4.1.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details (with versions)
      value: "OS: \nClient: \nEnv (Docker/K8s): "
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: related
    attributes:
      label: Related issues
      description: Mention if any related issues!
    validations:
      required: false
