name: "❌ Report a Bug"
description: Create an issue if something does not work as expected.
labels: ["Priority/Normal", "Type/Bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Tell us how you encountered the bug!
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: affected
    attributes:
      label: Affected Component/Version
      description: What version of our software are you running?
      options:
        - APIM/2.6.0
        - APIM/3.2.0
        - APIM/4.0.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details (with versions)
      placeholder: Tell us how you encountered the bug!
      value: "OS: <br>Client: <br>Env (Docker/K8s): "
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
