name: "❌ Report a Bug"
description: Create an issue if something does not work as expected.
labels: ["Priority/Normal", "Type/Bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Tell us how you encountered the bug!
    validations:
      required: true
  - type: dropdown
    id: affected
    attributes:
      label: Affected Component/Version
      options:
        - APIM/2.6.0
        - APIM/3.0.0
        - APIM/3.1.0
        - APIM/3.2.0
        - APIM/4.0.0
        - APIM/4.1.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details (with versions)
      value: "OS: \nClient: \nEnv (Docker/K8s): "
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: related
    attributes:
      label: Related issues
      placeholder: Mention if any related issues!
