on:
  issues:
    types: [opened]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if:
      ${{!(contains(github.event.issue.body, 'Affected Component/Version'))}}
    steps:
      - run: echo Affected label is not set
      - run: gh issue comment $ISSUE --body "This issue has Affected/{Component}/{Version} label"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
