on:
  issues:
    types: [labeled]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if:
      ${{(contains(github.event.issue.labels.*.name, 'Affected/APIM'))}}
    steps:
      - run: echo Labels are not properly set
      - run: gh issue edit $ISSUE --add-label "Component/APIM"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
